//πÿº¸÷°≤Â÷µº∆À„
void VertexMain(float3 normalA:NORMAL,
				float3 positionA:POSITION,
				float3 normalB:TEXCOORD2,
				float3 positionB:TEXCOORD1,
				float2 iTexCoord:TEXCOORD0,
				out float3 ojbPos:TEXCOORD2,
				out float3 ojbNormal:TEXCOORD1,
				out float2 oTexCoord:TEXCOORD0,
				uniform float weight,
				uniform float4x4 changeCoordMatrix,
				out float4 oPosition:POSITION
				)
{
	oPosition = mul(changeCoordMatrix, float4(lerp(positionA, positionB, weight), 1));
	ojbPos = oPosition.xyz;
	ojbNormal = normalize(lerp(normalA, normalB, weight));
	oTexCoord = iTexCoord;
}