void FragmentMain(float2 texCoord:TEXCOORD0, 
					float4 iColor:COLOR,
					float fogExponent:TEXCOORD1,

					uniform sampler2D textureParameter:TEX0,
					uniform float3 fogColor,

					out float4 oColor:COLOR)
{
	float fogFactor = exp2(-abs(fogExponent));
	float4 tempColor = iColor * tex2D(textureParameter, texCoord);

	oColor.xyz = lerp(fogColor, tempColor.xyz, fogFactor);
	oColor.w = iColor.w;
}